### ISSUE TITLE
DateTimeValidator: Change time regex to allow any number of decimal places after seconds

### ISSUE THREAD

**Issue by the-infinity** [binary-butterfly/validataclass#109]
At the moment, the DateTime validator throws an ValidationError if a date-time string contains nanoseconds. This is correct from a Python perspective, Python does not support nanoseconds. ISO date-time supports any fraction of time, though, which includes nanoseconds (and even less then that. Therefore, nanoseconds can be expected input if the API is used for APIs published to external sources if both partners agreed on ISO date-time. 

As Python datetime is not capable of nanoseconds (and, in almost all cases, it does not make sense to use them in APIs anyway, because clocks are usually not in sync on nanosecond-level), I would suggest to add an option to DateTime validation to accept and then just ignore nanoseconds.

Example: `2024-04-04T13:47:25.140496655Z` is a valid datetime, but throws an exception in validataclass.

**Comment by binaryDiv** [comment]
I wouldn't add an option for that. `datetime.fromisoformat()` supports input with arbitrary precision (including your example):

```
>>> datetime.fromisoformat('2024-04-04T13:47:25.140496655Z')
datetime.datetime(2024, 4, 4, 13, 47, 25, 140496, tzinfo=datetime.timezone.utc)
>>> datetime.fromisoformat('2024-04-04T13:47:25.14049665512313123123123123Z')
datetime.datetime(2024, 4, 4, 13, 47, 25, 140496, tzinfo=datetime.timezone.utc)
```

However, we currently use a regex before that to check the format: `r'(\d{2}:\d{2}:\d{2}(\.\d{3}(\d{3})?)?)'` (this is only for the time part).

So it currently allows `12:34:56`, `12:34:56.123` and `12:34:56.123456` but nothing in between or longer than that.

I'd argue that there is no harm in extending that to not only allow more decimal places, but also to allow just *any* number of decimal places, including `.1`, `.1234` etc... So we could just change the time regex to `r'(\d{2}:\d{2}:\d{2}(\.\d+)?)'`

What do you think? @the-infinity

**Comment by the-infinity** [comment]
Oh, did not expect this behavior, but: then your solution sounds really nice, because it would be the standard Python behavior to just throw away nanoseconds and beyond.

**Comment by flauschzelle** [comment]
Turns out that 

> `datetime.fromisoformat()` does support input with arbitrary precision (including your example):
> 
> ```
> >>> datetime.fromisoformat('2024-04-04T13:47:25.140496655Z')
> datetime.datetime(2024, 4, 4, 13, 47, 25, 140496, tzinfo=datetime.timezone.utc)
> >>> datetime.fromisoformat('2024-04-04T13:47:25.14049665512313123123123123Z')
> datetime.datetime(2024, 4, 4, 13, 47, 25, 140496, tzinfo=datetime.timezone.utc)
> ```

is only true for Python 3.11 and newer versions. So for compatibility with older versions, any non-zero amount of decimal places should be clipped/padded to exactly 6 before calling `datetime.fromisoformat()` on the modified input. 

(3 places would also be accepted, but padding them to 6 doesn't hurt and then we have fewer special cases to handle)
