### ISSUE TITLE
RegexValidator with output templates

### ISSUE THREAD

**Issue by binaryDiv** [binary-butterfly/validataclass#18]
This can be either implemented by adding a parameter `output_template` (or similar) to the existing `RegexValidator`, or by creating a new validator class (`RegexReplaceValidator`, `RegexTemplateValidator`?) based on `RegexValidator`:

Allow to specify "output templates" for regex validation, which uses `match.expand(output_template)` to return a templated string instead of the unmodified input string.

**Comment by lahdjirayhan** [comment]
Just to let everyone know, I'm working on this one!

:)
