### ISSUE TITLE
EmailValidator: Add parameter "allow_empty"

### ISSUE THREAD

**Issue by binaryDiv** [binary-butterfly/validataclass#86]
Add a boolean parameter `allow_empty` (default: False) to the `EmailValidator`.

If set, allow the empty string as input (and return an empty string).

(Maybe add the same parameter to `RegexValidator` as well?)

**Comment by TomasHalgas** [comment]
Hi, could I work also on this issue?
Thanks

**Comment by TomasHalgas** [comment]
I have implemented it, so could you please assign it to me?

**Comment by binaryDiv** [comment]
Hey @TomasHalgas, sorry for the late reply!

Sure, feel free to create a pull request. :)

**Comment by TomasHalgas** [comment]
Pull request created #89.
Parameter "allow_empty" added for both RegexValidator and EmailValidator.

**Comment by binaryDiv** [comment]
Implemented in #89 by @TomasHalgas :)
